package r507.app.application.accessingdatamysql;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/article") // This means URL's start with /demo (after Application path)
public class ArticleController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ArticleRepository articleRepository;
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private AuteurRepository auteurRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewArticle (@RequestBody CreateArticle createArticle) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    Article n = new Article(auteurRepository.findById(createArticle.getAuteur()).get());
    n.setTitre(createArticle.getTitre());
    n.setContenu(createArticle.getContenu());
    n.setDatePublication();
    articleRepository.save(n);
    return "Saved";
  }

  @PutMapping(path="/modify") // Map ONLY POST Requests
  public @ResponseBody String modifyArticle (@RequestBody ModifyArticle modifyArticle) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    Article n = articleRepository.findById(modifyArticle.getId()).get();
    if(modifyArticle.getTitre()!=null){
      n.setTitre(modifyArticle.getTitre());
    }
    if(modifyArticle.getContenu()!=null){
      n.setContenu(modifyArticle.getContenu());
    }
    articleRepository.save(n);
    return "Modified";
  }

  @DeleteMapping(path="/delete") // Map ONLY POST Requests
  public @ResponseBody String deleteArticle (@RequestBody DeleteArticle deleteArticle) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    articleRepository.delete(articleRepository.findById(deleteArticle.getId()).get());
    return "Deleted";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Article> getAllArticles() {
    // This returns a JSON or XML with the users
    return articleRepository.findAll();
  }
}